### ISSUE TITLE
Link Target Mismatch

### ISSUE THREAD

**Issue by dhelafrank** [godspowerufot/offficial-Nacos-Website#2]
![Screenshot from 2024-03-17 10-32-53](https://github.com/godspowerufot/offficial-Nacos-Website/assets/87214555/95105462-a053-4793-a8a5-952e5bb8e83b)
'View Nacos Gallery' Link directs to Google Maps instead of what i think should be a gallery page

**Comment by godspowerufot** [comment]
I just made a chane now check
