### ISSUE TITLE
Invalid Data as Related To Event

### ISSUE THREAD

**Issue by dhelafrank** [godspowerufot/offficial-Nacos-Website#3]
![image](https://github.com/godspowerufot/offficial-Nacos-Website/assets/87214555/7c58b886-660b-48f5-b5ec-8962dcc47aab)
I don't know if those are placeholders; but i think the data used for the rendering is invalid.
Live data used, should be reflecting the current event state.

A possible fix i'd recommend is JSON file containing information that will be used for the rendering

**Comment by godspowerufot** [comment]
noted the image of the exco and people to used are not yet given we will see to that ... let's hold on to the exco to give us images

**Comment by dhelafrank** [comment]
Okay 👍
